frontend_deck_keeper_index:
    pattern:    /
    defaults:   { _controller: JackDeckKeeperBundle:Card:index }

frontend_deck_keeper_cardset_index:
    pattern:    /sets
    defaults:   { _controller: JackDeckKeeperBundle:CardSet:index }
